site_name: FinRL Documentation
site_description: Comprehensive documentation for FinRL - A Deep Reinforcement Learning Library for Financial Markets
site_author: FinRL Team
site_url: https://github.com/AI4Finance-Foundation/FinRL

repo_name: AI4Finance-Foundation/FinRL
repo_url: https://github.com/AI4Finance-Foundation/FinRL
edit_uri: edit/master/docs/

copyright: Copyright &copy; 2024 FinRL Team

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - API Reference:
    - Environment Classes: api/environments.md
    - Agent Classes: api/agents.md
  - Data & Features:
    - Data Format: data/format-requirements.md
  - Advanced Features:
    - Ensemble Methods: advanced/ensemble-methods.md
  - Examples & Tutorials:
    - Cryptocurrency Trading: examples/crypto-trading.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md